//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.StaticticsRepository {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistic", Namespace="http://schemas.datacontract.org/2004/07/StatisticService.Model")]
    [System.SerializableAttribute()]
    public partial class Statistic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ViewDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIdField, value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ViewDate {
            get {
                return this.ViewDateField;
            }
            set {
                if ((this.ViewDateField.Equals(value) != true)) {
                    this.ViewDateField = value;
                    this.RaisePropertyChanged("ViewDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StaticticsRepository.IStatService")]
    public interface IStatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/AddStatitics", ReplyAction="http://tempuri.org/IStatService/AddStatiticsResponse")]
        int AddStatitics(Manager.StaticticsRepository.Statistic statistic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/AddStatitics", ReplyAction="http://tempuri.org/IStatService/AddStatiticsResponse")]
        System.Threading.Tasks.Task<int> AddStatiticsAsync(Manager.StaticticsRepository.Statistic statistic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/FindImageStats", ReplyAction="http://tempuri.org/IStatService/FindImageStatsResponse")]
        Manager.StaticticsRepository.Statistic[] FindImageStats(string imageId, string authorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/FindImageStats", ReplyAction="http://tempuri.org/IStatService/FindImageStatsResponse")]
        System.Threading.Tasks.Task<Manager.StaticticsRepository.Statistic[]> FindImageStatsAsync(string imageId, string authorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/FindAll", ReplyAction="http://tempuri.org/IStatService/FindAllResponse")]
        Manager.StaticticsRepository.Statistic[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatService/FindAll", ReplyAction="http://tempuri.org/IStatService/FindAllResponse")]
        System.Threading.Tasks.Task<Manager.StaticticsRepository.Statistic[]> FindAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatServiceChannel : Manager.StaticticsRepository.IStatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatServiceClient : System.ServiceModel.ClientBase<Manager.StaticticsRepository.IStatService>, Manager.StaticticsRepository.IStatService {
        
        public StatServiceClient() {
        }
        
        public StatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddStatitics(Manager.StaticticsRepository.Statistic statistic) {
            return base.Channel.AddStatitics(statistic);
        }
        
        public System.Threading.Tasks.Task<int> AddStatiticsAsync(Manager.StaticticsRepository.Statistic statistic) {
            return base.Channel.AddStatiticsAsync(statistic);
        }
        
        public Manager.StaticticsRepository.Statistic[] FindImageStats(string imageId, string authorName) {
            return base.Channel.FindImageStats(imageId, authorName);
        }
        
        public System.Threading.Tasks.Task<Manager.StaticticsRepository.Statistic[]> FindImageStatsAsync(string imageId, string authorName) {
            return base.Channel.FindImageStatsAsync(imageId, authorName);
        }
        
        public Manager.StaticticsRepository.Statistic[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<Manager.StaticticsRepository.Statistic[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
    }
}
